development:
  adapter: postgresql
  encoding: utf8
  database: angular2-example_development
  pool: 5
  timeout: 5000
  username: postgres
  password: 1

test:
  adapter: postgresql
  encoding: utf8
  database: angular2-example_test
  pool: 5
  timeout: 5000
  username: postgres
  password: 1

production:
  adapter: postgresql
  encoding: utf8
  database: angular2-example
  pool: 5
  timeout: 5000
  username: postgres
  password: 1
