export * from './components/hello/hello.component';
export * from './components/products/products.component';
export * from './components/product_form/product_form.component';
export * from './components/product_create/product_create.component';
export * from './components/product_detail/product_detail.component';
export * from './components/customers/customers.component';
export * from './components/customer_form/customer_form.component';
export * from './components/customer_create/customer_create.component';
export * from './components/customer_detail/customer_detail.component';